services:
  neo4j:
    image: neo4j:5-community
    environment:
      NEO4J_AUTH: neo4j/testpass
    ports:
      - "7687:7687" # bolt
      - "7474:7474" # browser
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
  neo4j_logs: